#PRODUCE A SCATTERPLOT DEPICTING LIFE EXPECTANCY AND FERTILITY RATE
#STATISTICS BY COUNTRY REGION FOR 1960 AND 2013
#Life expectancy data generated by executing vector code in other hwmk file

#import csv file
getwd()
csv <- read.csv("P2-Section5-Homework-Data.csv")

#filter csv to split data into 2 data frames for 1960 and 2013
head(csv)

df_1960 <- csv[csv$Year == 1960, ]
df_2013 <- csv[csv$Year == 2013, ]

nrow(df_1960)  #187 rows
nrow(df_2013)  #187 rows. Equal split.

#create life expectancy df
LE_1960 <- data.frame(Country_Code, Life_Exp=Life_Expectancy_At_Birth_1960)
LE_2013 <- data.frame(Country_Code, Life_Exp=Life_Expectancy_At_Birth_2013)

head(LE_1960)
head(LE_2013)
summary(LE_1960)
summer(LE_2013)

#merge life expectancy df with fertility rate df
merged_1960 <- merge(df_1960, LE_1960, by.x = "Country.Code", by.y="Country_Code")
merged_2013 <- merge(df_2013, LE_2013, by.x = "Country.Code", by.y="Country_Code")

head(merged_1960)
head(merged_2013)
str(merged_1960)
str(merged_2013)


#plot graphs using qplot() from ggplot2 package
qplot(data=merged_1960, x=Fertility.Rate, y=Life_Exp, color=Region,
      shape=I(18), alpha=I(.5), size=I(5),
      main="Life Expectancy vs Fertility Rate (1960)")
qplot(data=merged_2013, x=Fertility.Rate, y=Life_Exp, color=Region,
      shape=I(18), alpha=I(.5), size=I(5),
      main="Life Expectancy vs Fertility Rate (2013)")


#Takeaway: fertility rates dropped, life expectancy rose from 1960 to 2013
